version: '2'
services:
  service-phpmyadmin:
    image: phpmyadmin:latest
    container_name: service-phpmyadmin
    restart: always
    networks:
      - service_network
    ports:
      - "9999:80"
    environment:
      UPLOAD_LIMIT: 1000000000
    volumes:
      - ./conf/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

networks:
  service_network:
    external: true
